# -*- coding:utf8  -*-
from config import db

class NikeData(db.Model):
    # __tablename__ = "nike_data"
    odd_number = db.Column(db.String(50), unique=False, nullable=False)
    bu = db.Column(db.String(3), unique=False, nullable=True)
    picklist = db.Column(db.String(50), unique=True, nullable=False, primary_key=True)
    gi_date = db.Column(db.String(50), unique=False, nullable=False)
    load_city = db.Column(db.String(50), unique=False, nullable=False)
    unload_city = db.Column(db.String(50), unique=False, nullable=True)
    customer_code = db.Column(db.String(50), unique=False, nullable=False)
    unload_address = db.Column(db.String(300), unique=False, nullable=True)
    carton = db.Column(db.String(50), unique=False, nullable=False)
    unit = db.Column(db.String(50), unique=False, nullable=False)
    transport = db.Column(db.String(50), unique=False, nullable=False)
    load_time = db.Column(db.String(50), unique=False, nullable=True)
    est_time = db.Column(db.String(50), unique=False, nullable=True)
    stage = db.Column(db.String(50), unique=False, nullable=False)
    carrier = db.Column(db.String(50), unique=False, nullable=True)
    act_time = db.Column(db.String(50), unique=False, nullable=True)
    track_mark = db.Column(db.String(50), unique=False, nullable=True)
    consign_mark = db.Column(db.String(50), unique=False, nullable=True)
    first = db.Column(db.String(50), unique=False, nullable=True)
    second = db.Column(db.String(50), unique=False, nullable=True)
    third = db.Column(db.String(50), unique=False, nullable=True)
    fourth = db.Column(db.String(50), unique=False, nullable=True)
    fifth = db.Column(db.String(50), unique=False, nullable=True)
    sixth = db.Column(db.String(50), unique=False, nullable=True)
    seventh = db.Column(db.String(50), unique=False, nullable=True)
    eighth = db.Column(db.String(50), unique=False, nullable=True)
    ninth = db.Column(db.String(50), unique=False, nullable=True)
    tenth = db.Column(db.String(50), unique=False, nullable=True)
    eleventh = db.Column(db.String(50), unique=False, nullable=True)
    twelfth = db.Column(db.String(50), unique=False, nullable=True)
    thirteenth = db.Column(db.String(50), unique=False, nullable=True)
    fourteenth = db.Column(db.String(50), unique=False, nullable=True)
    fifteenth = db.Column(db.String(50), unique=False, nullable=True)
    issue = db.Column(db.String(50), unique=False, nullable=True)
    customer_abbr = db.Column(db.String(200), unique=False, nullable=True)
    costomer_full = db.Column(db.String(200), unique=False, nullable=True)
    consignee = db.Column(db.String(200), unique=False, nullable=True)
    contact = db.Column(db.String(200), unique=False, nullable=True)
    phone = db.Column(db.String(200), unique=False, nullable=True)
    is_estreport = db.Column(db.String(50), unique=False, nullable=True)
    est_name = db.Column(db.String(50), unique=False, nullable=True)
    customer_type = db.Column(db.String(50), unique=False, nullable=True)

# 创建数据库表
db.create_all()
